# Generated by Django 3.1.1 on 2020-10-01 23:27

import agendas.validators
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField(validators=[agendas.validators.validador_dia])),
                ('horarios', django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(), help_text='Ex: 14:00,15:00,16:00', size=None)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendas', to='medicos.medico')),
            ],
        ),
    ]
